### ISSUE TITLE
Add the content of the Help Page in an HTML page to guide the user 

### ISSUE THREAD

**Issue by Polymnia** [julianrojas87/era-compatibility-check#9]
- UX requirements: Page with static content and some expandable sections:
        - Sections to collapse {Step #...}, {Under the hood}, {Other things to try}, {Explore the ERA Knowledge Graph}
        - It can be very similar to the mobile view of wikipedia, something similar to this: 
![mockup1](https://user-images.githubusercontent.com/5465275/99075125-3f883280-25b9-11eb-9cea-a5c31e875d1d.PNG)
.

**Comment by julianrojas87** [comment]
Fixed on #15
